services:
  wikimost:
    build:
      context: .
    image: wikimost-local
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - wikimost:/app/data/storage

  db:
    image: postgres:18-alpine
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql

  redis:
    image: redis:8-alpine
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  wikimost:
  db_data:
  redis_data:
